# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-03-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0002_auto_20161130_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentscansdb',
            name='userID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
